# LOAD DATASET

In [25]:
import pandas as pd
import numpy as np

In [26]:
path_file = r"D:\Universitas Brawijaya_Roganda\BELAJAR_MANDIRI\DataScience\Project\StudentPerformanceFactors\dataset\Cleaned_StudentPerformanceFactors.csv"

df = pd.read_csv(path_file)

In [27]:
display(df.head())
display(df.info())

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

<class 'pandas.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   str
 3   Access_to_Resources         6607 non-null   str
 4   Extracurricular_Activities  6607 non-null   str
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   str
 8   Internet_Access             6607 non-null   str
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   str
 11  Teacher_Quality             6607 non-null   str
 12  School_Type                 6607 non-null   str
 13  Peer_Influence              6607 non-null   str
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   str
 16  Parental_Education_Level    6607 non-null   str
 17  Distance_from_Home          6607 non-null   str
 18  Gender                      6607 non-null   str
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), str(13)
memory usage: 1.0 MB

None

# SPLIT DATASET

In [28]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=['Exam_Score'])
y = df['Exam_Score']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print ("Training set size:", X_train.shape)
print ("Testing set size:", X_test.shape)

Training set size: (5285, 19)
Testing set size: (1322, 19)

In [29]:
display(X_train.head())
display(y_train.head())

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender
5810,27,79,Low,High,Yes,8,63,High,Yes,2,Low,Medium,Public,Negative,5,No,College,Moderate,Female
1268,16,86,High,Medium,Yes,7,94,Medium,Yes,2,Low,High,Public,Neutral,3,No,High School,Moderate,Female
414,22,87,Low,Medium,No,8,83,Low,Yes,1,Low,Medium,Public,Neutral,1,No,College,Far,Male
4745,18,100,High,Medium,Yes,10,86,Medium,Yes,1,Medium,Medium,Public,Neutral,3,No,High School,Near,Male
654,35,78,High,Low,Yes,10,99,Medium,Yes,1,Low,Medium,Private,Positive,2,No,High School,Near,Male

5810    69
1268    69
414     66
4745    72
654     72
Name: Exam_Score, dtype: int64

In [30]:
display(X_test.head())
display(y_test.head())

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender
743,20,71,Medium,Low,No,7,87,High,Yes,1,Medium,Medium,Public,Negative,5,No,High School,Near,Male
5551,22,71,Medium,Low,Yes,7,98,Low,Yes,2,Low,High,Public,Neutral,2,No,High School,Moderate,Female
3442,21,91,High,Medium,Yes,6,53,High,Yes,1,Medium,Medium,Public,Positive,3,No,Postgraduate,Near,Female
6571,12,91,Medium,Low,Yes,8,81,Low,Yes,0,Low,Low,Public,Positive,4,No,High School,Moderate,Male
4204,21,63,Low,High,Yes,8,95,Medium,Yes,2,High,Medium,Public,Neutral,5,No,High School,Near,Male

743     65
5551    65
3442    71
6571    64
4204    66
Name: Exam_Score, dtype: int64

In [32]:
display (y_train.describe())
print("--------")
display (y_test.describe())

count    5285.000000
mean       67.214948
std         3.920622
min        56.000000
25%        65.000000
50%        67.000000
75%        69.000000
max       100.000000
Name: Exam_Score, dtype: float64

--------

count    1322.000000
mean       67.317700
std         3.761087
min        55.000000
25%        65.000000
50%        67.000000
75%        70.000000
max        98.000000
Name: Exam_Score, dtype: float64